name: Deploy service
description: This workflow creates the k8s manifest file and deploys it to EKS

inputs:
  # === Required
  app_name:
    description: The application name
    required: true
  service_type:
    description: The service type. I.e. webservice
    required: true
  instance:
    description: What instance to deploy to. I.e. development
    required: true
  namespace:
    description: The Kubernetes namespace
    required: true
  docker_image:
    description: The docker image tag URL
    required: true
  aws_region:
    description: AWS region where the EKS cluster lives
    required: true

  # === Optional
  replicas:
    description: How many replicas you need
    required: false
  port:
    description: The Kubernetes service port
    required: false
  container_port:
    description: The Kubernetes application pod port
    required: false
  ingress:
    description: Should it has its own ingress?
    required: false
  ingress_host:
    description: The host connected to the ingress
    required: false
  ingress_path:
    description: The application path
    required: false

  # === Secret time, these secrets is required and needed to make the deploy work
  AWS_ACCESS_KEY_ID:
    description: The AWS access key
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: The AWS secret key
    required: true
  KUBE_CONFIG:
    description: The base64 encoded kube config file
    required: true

runs:
  using: composite
  steps:
    - name: Create the Manifest filename
      shell: bash
      id: manifest
      run: echo "::set-output name=filename::${{ inputs.instance }}.k8s.manifest.yaml"

    - uses: dignio/generate-manifest@v2.1.0
      name: Generate the Kubernetes manifest
      id: generate_manifest
      with:
        # === These must be specified for the action to work
        app_name: ${{ inputs.app_name }}
        service_type: ${{ inputs.service_type }}
        instance: ${{ inputs.instance }}
        namespace: ${{ inputs.namespace }}
        docker_image: ${{ inputs.docker_image }}

        # === These are optional
        replicas: ${{ inputs.replicas }}
        port: ${{ inputs.port }}
        container_port: ${{ inputs.container_port }}
        ingress: ${{ inputs.ingress }}
        ingress_host: ${{ inputs.ingress_host }}
        ingress_path: ${{ inputs.ingress_path }}

    - name: Echo the manifest output to a file
      shell: bash
      run: "echo ${{steps.generate_manifest.outputs.manifest}} | base64 --decode > $GITHUB_WORKSPACE/${{ steps.manifest.outputs.filename }}"

    - name: Upload the manifest as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.instance }}-k8s-manifest"
        path: "${{ steps.manifest.outputs.filename }}"

    # === Configure AWS for the deploy
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws_region }}

    - name: Authenticate with Kubernetes
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ inputs.KUBE_CONFIG }}

    - name: Deploy to Kubernetes
      uses: Azure/k8s-deploy@v1
      with:
        namespace: ${{ inputs.namespace }}
        manifests: |
            ${{ steps.manifest.outputs.filename }}
        kubectl-version: 'latest'
