name: GitHub Actions Demo
on:
  push:
    branches:
      - main
      - release/**
      - hotfix/**
      - experimental/**
      - test/**
  pull_request:
    types: [ opened, synchronize ]
jobs:
  build:
    # The type of runner that the job will run on
    name: "Create manifest file"
    runs-on: ubuntu-latest

    steps:
      - uses: dignio/generate-manifest@v1.0.1
        name: Generate the Kubernetes manifest
        id: generate_manifest
        with:
          # These must be specified for the action to work
          app_name: prevent-ui
          namespace: development
          docker_image: 833870238474.dkr.ecr.eu-north-1.amazonaws.com/prevent-ui:9628f958eb4a69571cfee558624fa0a33fa49c4f

          # These are optional
          replicas: 1
          port: 80
          container_port: 80
          ingress: true
          ingress_host: prevent.dev.dignio.dev
          ingress_path: /

      - name: echo the manifest output
        run: "echo ${{steps.generate_manifest.manifest}}"