name: GitHub Actions Demo
on:
  push:
    branches:
      - main
      - release/**
      - hotfix/**
      - experimental/**
      - test/**
  pull_request:
    # types: [ opened, synchronize ]
jobs:
  build:
    # The type of runner that the job will run on
    name: "Create manifest file"
    runs-on: ubuntu-latest

    steps:
      - uses: dignio/generate-manifest@v1
        name: Generate the Kubernetes manifest
        id: generate_manifest
        with:
          # These must be specified for the action to work
          app_name: prevent-ui
          namespace: development
          docker_image: 833870238474.dkr.ecr.eu-north-1.amazonaws.com/prevent-ui:9628f958eb4a69571cfee558624fa0a33fa49c4f

          # These are optional
          replicas: 1
          port: 80
          container_port: 80
          ingress: true
          ingress_host: prevent.dev.dignio.dev
          ingress_path: /

      - name: Echo the manifest output to a tmp file
        run: "echo ${{steps.generate_manifest.outputs.manifest}} | base64 --decode > $GITHUB_WORKSPACE/k8s.manifest.yaml"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to the EKS cluster
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          # Get the kubectl binary
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
          chmod +x kubectl

          # Handle the kube config
          echo ${KUBE_CONFIG} | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

          # Apply to the EKS cluster
          ./kubectl apply -f $GITHUB_WORKSPACE/k8s.manifest.yaml


#      - name: Deploy to EKS cluster
#        uses: Consensys/kubernetes-action@master
#        env:
#          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: eu-north-1
#        with:
#          args: apply -f k8s.manifest.yaml

#      - name: Authenticate with Kubernetes
#        uses: azure/k8s-set-context@v1
#        with:
#          method: kubeconfig
#          kubeconfig: ${{ secrets.KUBE_CONFIG }}

#      - name: Deploy to Kubernetes
#        uses: Azure/k8s-deploy@v1
#        with:
#          manifests: |
#              $GITHUB_WORKSPACE/k8s.manifest.yaml
#          kubectl-version: 'latest'